### ISSUE TITLE
HTMLエディタをMarkdown エディタにしたい

### ISSUE THREAD

**Issue by katsusuke** [nnh/eclipro#12]
## メリット
- 記法に制限があり、見出し、リスト(数字つき、無し)、テーブル、画像挿入程度しか表現が出来ないため、パースが簡単
  - Word 等に変換した場合に見栄えを整えやすい
  - 表現方法に制限が多いため、他フォーマットへの変換が用意
  - データとしての再利用もし易い
- HTMLにも簡単に変換できる
- Markdown 記法に慣れていれば高速に入力可能

## デメリット
- Markdown を書く時は、wysiwyg エディタを使うよりタグを直打ちした方が効率敵なため、wysiwyg エディタで良いものが無いかもしれない

## 候補
- https://yabwe.github.io/medium-editor/
  - テキストを選択すると修飾のツールバーが出てくる
  - 初めからは出ていないので、Word から比べて操作感の違いが許容できるか?
  - テーブルは 右記のプラグインで対応可能 https://yabwe.github.io/medium-editor-tables/

**Comment by R-Y** [comment]
現状ではmarkdownを使わない、ということでcloseします。
