### ISSUE TITLE
Section のソート順を考えたい

### ISSUE THREAD

**Issue by katsusuke** [nnh/eclipro#14]
Section#no に title compliance、テキスト、no の3値が入っており、文脈によって動作を変えている。
ソート順と表示対象の概念が混在しているので整理したい

**Comment by katsusuke** [comment]
Content#no も同様の機能が存在するため、concern で保持したい

**Comment by R-Y** [comment]
すみません、protocolsとcontentsのviewを調整した時に、
titleとcomplianceをcontents一覧から削除（元々protocolの情報しかなく、編集することもなかったのでprotocol詳細へ移動）
の結果、両者が混ざるタイプのソートはなくなりました。
現時点では数字（0, 1, 1.1, 1.2 ... ）のソートのみです。

seedとsection.rbから該当部分を削除するとして、
他の箇所で気になる、こうした方がいい、という部分はありますでしょうか？

**Comment by katsusuke** [comment]
確認しました。良さそうなのでクローズ致します

**Comment by katsusuke** [comment]
reopen します

**Comment by R-Y** [comment]
終了したのでcloseします。
