### ISSUE TITLE
ナビゲーターの[プロトコルを新規作成]の右側に[ヘルプ]リンクを作成したい

### ISSUE THREAD

**Issue by tosh13** [nnh/eclipro#16]
https://docs.google.com/document/d/e/2PACX-1vRC2HhdHbtB6M94VMRe9M9U_n05ZGKejh_cot9yc8S78bqX0NThv1_cluiUkBYLeNuiF9D2oLFr1Gs5/pub
こちらへのリンクとして下さい。

**Comment by R-Y** [comment]
bd2e08e7981d0157c91890e7153ac70d3c01fcc0

上記コミットで対応しました。
