### ISSUE TITLE
Word 形式で出力したい

### ISSUE THREAD

**Issue by katsusuke** [nnh/eclipro#2]
## 課題
doc 形式への対応が必要かどうか?

doc 形式はMS Word 2003 の形式だが、2003 は既にサポートが切れていて、サポートが不要なのではと考えております

**Comment by tosh13** [comment]
docxのみで対応はOKです。

**Comment by katsusuke** [comment]
https://github.com/alphabetum/pandoc-ruby を使ってみる?
- heroku で動かないかも
- HTMLよりもMarkdownの方が正確にコンバートできると思われるため、可能であればHTMLエディタをMarkdown エディタに変更した方が良い

**Comment by R-Y** [comment]
https://github.com/nickfrandsen/htmltoword
このgemを使ってみたのですが、画像挿入が現時点で未対応のようでした。
