### ISSUE TITLE
エディタメニューのテキストカラー、バックグラウンドカラー、エモーティコンを削除

### ISSUE THREAD

**Issue by R-Y** [nnh/eclipro#20]

**Comment by R-Y** [comment]
dea3dfc46e15afddb73fa19817178472f4fae6e2

上記コミットで対応しました。

**Comment by tosh13** [comment]
https://dev-eclipro.herokuapp.com/protocols/11
反映されていないようです

**Comment by R-Y** [comment]
@tosh13 
すみません、herokuを更新したのはこの修正を行う前でした。
先ほどもう一度heroku更新を行いました。
