### ISSUE TITLE
herokuでエラーが出る

### ISSUE THREAD

**Issue by R-Y** [nnh/eclipro#47]
- migrateでNilClassエラー
  - participations.principal_investigatorがnilの時があるようなので、nilの時の対処を入れる

上記対応後に
- reference.docxアップロードでLoadError (cannot load such file -- aws-sdk-s3 (You may need to install the aws-sdk-s3 gem))

@katsusuke 
aws-sdk-s3のgemを入れろと言われているようなのですが、
https://devcenter.heroku.com/articles/paperclip-s3
公式見ててもaws-sdk gemの記述になってているのですが、素直にaws-sdk-s3 gemを入れればよいのでしょうか…？
それとも他の設定が間違っているのでしょうか。

**Comment by katsusuke** [comment]
> reference.docxアップロードでLoadError (cannot load such file -- aws-sdk-s3 (You may need to install the aws-sdk-s3 gem))

上記のエラーはローカルで出るという事でしょうか？
aws-sdk-s3 のgem はメンテが微妙で、以前何かの機能が動かなくて、fog というgem を利用したことがあります。

**Comment by R-Y** [comment]
@katsusuke 
いえ、reference.docxを確認しようと、現在のmasterをプッシュしたheroku上で出ています。
paperclip自体は画像アップロードでも使用しており、当時は問題なくできていたのですが…
今確認したら画像アップロードでも同様のエラーが出るようになっています。

**Comment by katsusuke** [comment]
@R-Y 
すみません。同様の事象は経験が無いです。調査をお願い致します。

**Comment by R-Y** [comment]
@katsusuke 
https://github.com/thoughtbot/paperclip/commit/572bba0ec2a8b3b9f56d845a2cebecff34b5a11b#diff-97bdf5a528539d17998d2f825cea1109
paperclip側がaws-sdkからaws-sdk-s3に変更したようですので、そちらに変更してみます。
問題が出るようならfogを視野に入れる…ということでもよいでしょうか？

**Comment by katsusuke** [comment]
@R-Y 
https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/storage/fog.rb
fog だとこのあたりかな・・・

**Comment by R-Y** [comment]
@katsusuke 
すみません、それはこの時点でfogに変えたほうがよい、という意図でしょうか？
一応ローカルでaws-sdk-s3に変更してenv設定した状態で動作確認はできたのですけれども。

**Comment by katsusuke** [comment]
@R-Y 動けばいいと思いますので、現時点でのgem 変更は不要です
何回か動かない様な自体が発生した段階で検討すればよいかと思います

**Comment by R-Y** [comment]
herokuで動作確認できたのでcloseします
