### ISSUE TITLE
develop ブランチで開発していることについて

### ISSUE THREAD

**Issue by katsusuke** [nnh/eclipro#5]
@R-Y 
現在 develop ブランチで開発を行っているようですが、これには何か意図がありましたでしょうか?

**Comment by R-Y** [comment]
@katsusuke 
単に作業中だったのと、パブリックリポジトリだったのでワンクッション置きたかった、という感じです。
斎藤さんからはこちらに任せると言われたので、masterの方が都合がいいならマージします。

**Comment by katsusuke** [comment]
ではmaster にマージお願いいたします。
