### ISSUE TITLE
アプリが落ちたら通知して欲しい

### ISSUE THREAD

**Issue by tosh13** [nnh/eclipro#53]
アプリが落ちたら吉田さんに通知が送られ自動的に対応が開始できるようにして欲しい。

**Comment by R-Y** [comment]
@katsusuke 
heroku上で使うことを考えるなら[アドオン](https://elements.heroku.com/addons)で
単純にメール通知するなら[exception_notification](https://github.com/smartinez87/exception_notification)が出てきますが、
何かおすすめはありますでしょうか？

**Comment by katsusuke** [comment]
Ptosh ではこれを使ってます
https://rollbar.com/error-tracking/ruby/
https://newrelic.com/

**Comment by R-Y** [comment]
アドオン追加済ですのでcloseします
