### ISSUE TITLE
React、table描画のリファクタリング

### ISSUE THREAD

**Issue by R-Y** [nnh/eclipro#65]
現在、reactでtableタグを丸ごと描画しているけれど、thead部分はslimに書いてtbody部分だけreactで描画するようにしたい。
```
<table>
  <thead>(略)</thead>
  <tbody>(略)</tbody>　←ここだけreactで描画するように変更したい
</table>
```
```history.jsx
render () {
  const head = ...
  const body = ...
}
return (
  <table>
    <thead>{head}</thead>
    <tbody>{body}</tbody>
  </table>
)
↓
render () {
  const body = ...
}
return body:
```

**Comment by katsusuke** [comment]
body だけ別ファイルにしてもコンポーネントの再利用性は特に上がらなそうですが、目的は何でしょうか？

**Comment by R-Y** [comment]
静的な部分（thead）までreactで書くのはどうなんだろう、という感じがするのですけど、特に問題はないのでしょうか？
あとは単純にjavascriptのコードが減るかな、と（その分slimで少し増えますが…）

**Comment by katsusuke** [comment]
table はtbody だけで存在することができないので、その設計ですと、js 側(tbody)とrails 側(その他)にコードが散らばるため良くないです。
同一の階層のコードは同じ場所に存在すべきです。

table は 
thead => クラス
tbody => インスタンスの配列

から構成されているので、rails と js の境界でRailsクラスとインスタンスの配列情報を渡す方法があると、モデル情報に責務を持つrails 側と、view 側に責務を持つjs 側で分割できて良さそうに思います。

=> 不勉強なので知らないのですが既にあるかも・・・rails 側からは型情報を GraphQL とかで渡して、JS側でクラス情報を復元する的な

**Comment by R-Y** [comment]
当issueの考え方では触らない方が良さそうなのでこのまま閉じます。
- tbodyのみの描画に変更しても再利用性があがるわけではない。むしろコードが散らばるので良くない
- ↓のようにtable出力を抽象化したいけれどもjsonに型情報がないのでできない
（良い方法が見つかったら別issueを作成して対応する）
```
def tablize(klass, columns, objects)
  content_tag :table do
    thead = content_tag(:thead) do
      content_tag(:tr) do 
        safe_join columns.map { |c| content_tag(:th) { klass.human_attribute_name c } }
      end
    end
    tbody = content_tag(:tbody) do 
      trs = objects.map do |o| 
        content_tag(:tr) do
          safe_join columns.map { |c| content_tag(:td) { o.send(c) } }
      safe_join trs
    end
    safe_join [thead, tbody]
  end
end
```
