### ISSUE TITLE
jQuery を撤廃したい

### ISSUE THREAD

**Issue by katsusuke** [nnh/eclipro#66]
- jQuery に依存している箇所の調査
- AJAX ライブラリの選定
  - React コンポーネント内でのjQuery 利用箇所の置換

**Comment by katsusuke** [comment]
優先順位が低いのですが、他にやることが無いときにちょっとずつ進めたいです。

1. 作業の洗い出し
2. 複数PR にて作業を行う

**Comment by R-Y** [comment]
- jQuery に依存している箇所 … app/javascript/packs フォルダ内のexport.jsを除くjs/jsxファイル
    - comment.jsx
    - history.jsx
    - main.js
    - protocol.jsx
    - tiny_mce.js
- ajaxライブラリ
    - [SuperAgent](https://github.com/visionmedia/superagent)
    - [Fetch API](https://github.com/github/fetch)
などがあるようです。

@katsusuke 
複数PRにて作業を行う、とのことですが、ライブラリの導入とそれ以外のjQueryの撤廃、辺りで分割するのでしょうか？

**Comment by katsusuke** [comment]
@R-Y 

> ajaxライブラリ

https://caniuse.com/#feat=fetch
ネイティブのfetch で良さそうですね

> ライブラリの導入とそれ以外のjQueryの撤廃

それぞれのPRは、何からの機能が動作完了した状態をもって終了とすべきです。
ライブラリを導入(yarn add ?)だけだと、何らか動作可能な機能が完成しないので、PR終了の条件が難しそうですが、どの様なイメージになりますでしょうか？
終了条件が簡単そうな切り方としては例えば下記の様なイメージです

- jsx ファイルからjQuery を撤廃
- tiny_mce からjQuery を撤廃
- main.js からjQuery を撤廃

**Comment by R-Y** [comment]
@katsusuke 
すみません、言葉が足りませんでした。
ライブラリを追加してajax部分を書き換える、までがワンセットのつもりでした。

作業量が多いのでPRを切り分ける、という意味なのでしたら、清水さんが提案していただいたような分割で良いと思います。

**Comment by katsusuke** [comment]
よろしくお願いします

**Comment by katsusuke** [comment]
bootstrap もjQuery に依存している

**Comment by katsusuke** [comment]
IE11がnative のfetch APIに対応していないため whatwg-fetchを利用
