### ISSUE TITLE
過剰なJavascript 利用を避けたい

### ISSUE THREAD

**Issue by katsusuke** [nnh/eclipro#76]
リンクをクリックしたら 画面遷移をせずalert が出る処理がある
そもそも、View 側でチェックして、リンク非表示かつ、メッセージを画面に表示しておけばインタラクティブな処理は不要
https://github.com/nnh/eclipro/blob/master/app/javascript/packs/content_show.js#L37

同様にViewで完結可能な操作がJavascript 化されている部分をrails 単体での動作に変更したい

**Comment by katsusuke** [comment]
![eclipro](https://user-images.githubusercontent.com/624736/45281285-541c9c00-b512-11e8-93e9-352d191165aa.png)

**Comment by R-Y** [comment]
@katsusuke 
>同様にViewで完結可能な操作がJavascript 化されている部分をrails 単体での動作に変更したい
一通りjavascriptを見てみましたが、他に書き換えた方が良さそうな場所は見つけられませんでした。
清水さんからすると、どこが書き換えるべき場所と判断されるのでしょうか。

**Comment by katsusuke** [comment]
ちょっと思いついてないです。
思いついたら別途Issue 立てます。また吉田さんも見つけたらおしえてください
