### ISSUE TITLE
運用フローを整備したい

### ISSUE THREAD

**Issue by katsusuke** [nnh/eclipro#80]
## 背景
- いつどの様な変更が行われたかのトレーサビリティを持ちたい
- 現状担当者が少ないため最小の手順で行いたい
  - 利用者が増えてきたらそのタイミングでPtosh の様な方式(release -> 確認 -> 反映)を採用する可能性がある

## 運用
- リリースノートとして利用できるようなPRタイトルをつける
  - `[#issueid1][#issueid2] RELEASE_TITLE`
  - 例 `[#40] テンプレート毎にreference.docxを設定できるようにした`
  - https://github.com/nnh/eclipro/pulls?q=is%3Apr+is%3Aclosed この画面がリリースノートになるようにする
- 実装内容、リスクなどをPR のコメントにまとめる
- 複数のPRで一つのIssue を実装するケースがあるので、その場合、最後のPRでIssue の全ての実装内容をまとめる
- github flow を適応し マージ == リリースとする
  - heroku の機能を使い マージされたタイミングで本番適応を行う
  - Closed なPR == リリース履歴

## リスク

- ステージングサーバーと同じタイミングで本番適応されるため、サービス継続不能なバグが発生するとダウンタイムが発生する
  - CI、監視、バックアップで対策する

**Comment by katsusuke** [comment]
@tosh13 @R-Y 確認 & ご指摘お願いします

**Comment by tosh13** [comment]
OKです。宜しくおねがいします。

**Comment by katsusuke** [comment]
@tosh13 クローズさせていただきます
