### ISSUE TITLE
アップロード画像を永続化したい

### ISSUE THREAD

**Issue by R-Y** [nnh/eclipro#9]
tiny_mceエディタに画像を挿入した際、S3などに保存するようにしたい。

**Comment by katsusuke** [comment]
- tiny_mce の画面で画像のアップロードが動作すること
  - tiny_mce で作成したHTML文字列にURLが固定に入るので、動的にURLが変更される様なものは難しいかもしれない
  - heroku のアプリケーション経由でDLを行うと、巨大ファイルのダウンロード中にdyno を消費する
    - AWS移行?
- 閲覧者が閲覧できること

**Comment by katsusuke** [comment]
paperclip_database は更新がされておらず、rails5では動作しない
https://github.com/softace/paperclip_database/pull/20/commits/d223acccba4b815061468e0e7fa8e3c489797ee0#diff-5da9fe30651ff4dfeddbd73866805750

別の手段を探る
- DBストア
  - Paperclip + paperclip_database
  - Paperclip 以外
- Paperclip + S3ストア (S3直DLではなく、Controller 経由でファイルをDLする)
- Heroku やめる

**Comment by R-Y** [comment]
railsのファイルアップローダー（参考：https://www.ruby-toolbox.com/categories/rails_file_uploads.html）

- Paperclip（https://github.com/thoughtbot/paperclip）
　シンプルに使えるけれどメンテは怪しい。
　- DBストア https://github.com/softace/paperclip_database 更新停止中
- Carrierwave
　多機能（ただしそこまで必要ないと思います）。キャッシュが使える。
　- DBストア https://github.com/richardkmichael/carrierwave-activerecord 更新停止中
- Dragonfly
　Paperclip的に使えて、画像のリサイズがしやすい（今回は必要のない部分かと思います）。
- ReFile
　Carrierwaveの後継。ダイレクトアップロードなどが可能。
- Attachment fu
　最終更新が９年前なので完璧に止まってるようです。

基本的にどれもファイルシステムもしくはS3などに保存を想定しているようで、DBにバイナリで保存するような機能は外部gemもしくは自力になりそうです。
gemもgemで更新停止中だったりスターが一桁で利用者がほとんどいないような状態で、使えるものなのか判断に困る感じです。

**Comment by katsusuke** [comment]
更新が止まっているやつは除外して良いと思います。

公式でcontroller 経由でのファイルダウンロードををサポートしてるやつが良いですね

**Comment by R-Y** [comment]
Attachment fuを除く上記ライブラリ４つを確認してみましたが、どれも公式で用意してなさそうでした

**Comment by katsusuke** [comment]
Paperclip はこんなのがあるそうです
https://github.com/thoughtbot/paperclip/wiki/Restricting-Access-to-Objects-Stored-on-Amazon-S3

**Comment by R-Y** [comment]
すみません、send_dataなどがすでに組み込まれているかどうか、というような風に探していました。

paperclipの方はサンプルにredirect_toで書かれていてエディタ内で画像参照しようとするとどう動くのかはわかりませんが…carrierwaveのようにsend_fileかsend_dataすれば動く感じはするので、どちらも使えるとは思います。

**Comment by katsusuke** [comment]
とりあえずpaperclip で行きましょう
